### ISSUE TITLE
Can support -template arg?

### ISSUE THREAD

**Issue by fengxuway** [buoto/vim-gotests#6]
I offen use gotests with `-template testify`, just like: 

```
gotests -only "myFuncName" -w -template testify mycode.go
```
Can this plugin support the arg?

**Comment by fengxuway** [comment]
I create a merge request, check please~

https://github.com/buoto/gotests-vim/pull/7

**Comment by patrickquigley102** [comment]
+1 for this when you've time Buoto

**Comment by LucasChenPandaTW** [comment]
Create the PR here.
https://github.com/buoto/gotests-vim/pull/12
